# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
        args: ['-local', 'github.com/SphereStacking/silentcast']
      - id: go-mod-tidy
        args: ['-compat=1.21']
        files: '^app/go\.(mod|sum)$'
        pass_filenames: false
        always_run: false

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
        entry: bash -c 'cd app && golangci-lint run --config=.golangci.yml ./...'
        files: '^app/.*\.go$'
        pass_filenames: false
        always_run: false

  - repo: local
    hooks:
      - id: go-test
        name: go test
        entry: bash -c 'cd app && go test -v -race -tags "nogohook notray" ./...'
        language: system
        files: '^app/.*\.go$'
        pass_filenames: false

  # Commitizen disabled - project uses emoji prefixes instead
  # - repo: https://github.com/commitizen-tools/commitizen
  #   rev: v3.13.0
  #   hooks:
  #     - id: commitizen
  #       stages: [commit-msg]
