#!/bin/bash
# ticket-report.sh - Generate ticket status reports

set -e

TICKET_DIR="$(cd "$(dirname "$0")/../.." && pwd)/.ticket"
DATE=$(date +"%Y-%m-%d %H:%M")


# Generate report
echo "# Ticket Status Report"
echo ""
echo "Generated: $DATE"
echo ""

# Overall summary
echo "## Overall Summary"
echo ""

# Find all tickets excluding archive subdirectory
ALL_ACTIVE_TICKETS=$(find "$TICKET_DIR/tickets" -name "*.yml" -type f -not -path "*/archive/*" 2>/dev/null)
ALL_ARCHIVED_TICKETS=$(find "$TICKET_DIR/tickets/archive" -name "*.yml" -type f 2>/dev/null)

TOTAL_TODO=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: todo" {} 2>/dev/null | wc -l)
TOTAL_IN_PROGRESS=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: in_progress" {} 2>/dev/null | wc -l)
TOTAL_REVIEW=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: review" {} 2>/dev/null | wc -l)
TOTAL_TESTING=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: testing" {} 2>/dev/null | wc -l)
TOTAL_COMPLETED_IN_TICKETS=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: completed" {} 2>/dev/null | wc -l)
TOTAL_COMPLETED_ARCHIVED=$(echo "$ALL_ARCHIVED_TICKETS" | wc -l)
TOTAL_COMPLETED=$((TOTAL_COMPLETED_IN_TICKETS + TOTAL_COMPLETED_ARCHIVED))
TOTAL_BLOCKED=$(echo "$ALL_ACTIVE_TICKETS" | xargs -I {} grep -l "^status: blocked" {} 2>/dev/null | wc -l)

TOTAL_ACTIVE=$((TOTAL_TODO + TOTAL_IN_PROGRESS + TOTAL_REVIEW + TOTAL_TESTING + TOTAL_BLOCKED))
TOTAL_ALL=$((TOTAL_ACTIVE + TOTAL_COMPLETED))

echo "| Status | Count | Percentage |"
echo "|--------|-------|------------|"
printf "| Todo | %d | %.1f%% |\n" $TOTAL_TODO $(echo "scale=1; $TOTAL_TODO * 100 / $TOTAL_ALL" | bc)
printf "| In Progress | %d | %.1f%% |\n" $TOTAL_IN_PROGRESS $(echo "scale=1; $TOTAL_IN_PROGRESS * 100 / $TOTAL_ALL" | bc)
printf "| Review | %d | %.1f%% |\n" $TOTAL_REVIEW $(echo "scale=1; $TOTAL_REVIEW * 100 / $TOTAL_ALL" | bc)
printf "| Testing | %d | %.1f%% |\n" $TOTAL_TESTING $(echo "scale=1; $TOTAL_TESTING * 100 / $TOTAL_ALL" | bc)
printf "| Completed | %d | %.1f%% |\n" $TOTAL_COMPLETED $(echo "scale=1; $TOTAL_COMPLETED * 100 / $TOTAL_ALL" | bc)
printf "| Blocked | %d | %.1f%% |\n" $TOTAL_BLOCKED $(echo "scale=1; $TOTAL_BLOCKED * 100 / $TOTAL_ALL" | bc)
echo "|--------|-------|------------|"
printf "| **Total** | **%d** | **100.0%%** |\n" $TOTAL_ALL
echo ""

# Type breakdown
echo "## Type Distribution"
echo ""
echo "| Type | Count |"
echo "|------|-------|"

for type in feature bug refactor docs test chore; do
    COUNT=$(find "$TICKET_DIR/tickets" -name "*.yml" -type f -exec grep -l "^type: $type" {} \; 2>/dev/null | wc -l)
    [ "$COUNT" -gt 0 ] && echo "| ${type^} | $COUNT |"
done
echo ""

# Priority breakdown
echo "## Priority Distribution"
echo ""
echo "| Priority | Count |"
echo "|----------|-------|"

for priority in critical high medium low; do
    COUNT=$(find "$TICKET_DIR/tickets" -name "*.yml" -type f -exec grep -l "^priority: $priority" {} \; 2>/dev/null | wc -l)
    [ "$COUNT" -gt 0 ] && echo "| ${priority^} | $COUNT |"
done
echo ""

# Recent activity
echo "## Recent Activity"
echo ""
echo "### Recently Updated (Last 7 days)"
echo ""

SEVEN_DAYS_AGO=$(date -d "7 days ago" +%Y-%m-%d 2>/dev/null || date -v-7d +%Y-%m-%d)
RECENT_TICKETS=$(find "$TICKET_DIR/tickets" -name "*.yml" -type f -exec grep -l "^updated: \".*\"" {} \; | while read -r ticket; do
    UPDATED=$(grep "^updated:" "$ticket" | cut -d'"' -f2)
    if [[ "$UPDATED" > "$SEVEN_DAYS_AGO" ]]; then
        echo "$ticket"
    fi
done)

if [ -n "$RECENT_TICKETS" ]; then
    echo "| ID | Title | Status | Updated |"
    echo "|----|-------|--------|---------|"
    
    echo "$RECENT_TICKETS" | while read -r ticket; do
        ID=$(grep "^id:" "$ticket" | awk '{print $2}')
        TITLE=$(grep "^title:" "$ticket" | cut -d'"' -f2)
        STATUS=$(grep "^status:" "$ticket" | awk '{print $2}')
        UPDATED=$(grep "^updated:" "$ticket" | cut -d'"' -f2)
        printf "| %s | %.40s | %s | %s |\n" "$ID" "$TITLE" "$STATUS" "$UPDATED"
    done
else
    echo "No tickets updated in the last 7 days."
fi
echo ""

# Blocked tickets
echo "## Blocked Tickets"
echo ""

BLOCKED_TICKETS=$(find "$TICKET_DIR/tickets" -name "*.yml" -type f -not -path "*/archive/*" -exec grep -l "^status: blocked" {} \; 2>/dev/null)

if [ -n "$BLOCKED_TICKETS" ]; then
    echo "| ID | Title |"
    echo "|----|-------|"
    
    echo "$BLOCKED_TICKETS" | while read -r ticket; do
        ID=$(grep "^id:" "$ticket" | awk '{print $2}')
        TITLE=$(grep "^title:" "$ticket" | cut -d'"' -f2)
        printf "| %s | %.50s |\n" "$ID" "$TITLE"
    done
else
    echo "No blocked tickets."
fi
echo ""

echo "---"
echo ""
echo "*Report generated by ticket-report.sh*"