linters:
  enable-all: false
  disable-all: true
  enable: # please keep this alphabetized
    - bodyclose # checks if HTTP responses are properly closed
    - containedctx # checks best practice of not storing Context in structs
    - depguard # defines and checks for disallowed package imports
    - errcheck # [default] checks for code issues with error wrapping introduced in Go 1.13
    - errorlint # checks for unchecked error handling
    - gocritic # linter with many check items
    - gofmt # checks if go fmt has been applied
    - goimports # checks if goimports has been applied
    - gosec # checks various security aspects
    - gosimple # [default] checks for unnecessary code patterns
    - govet # [default] official go vet tool
    - ineffassign # [default] checks for unnecessary assignments
    - misspell # spell checker
    - nakedret # checks for naked returns in long functions
    # - paralleltest # checks for tests without t.Parallel() - TODO: enable after adding t.Parallel() to tests
    - rowserrcheck # checks if database/sql Rows errors are properly handled
    - sqlclosecheck # checks if sql.Rows and sql.Stmt are properly closed
    - staticcheck # [default] linter with many check items
    - unconvert # checks for unnecessary type conversions
    - unparam # checks for unused parameters
    - unused # checks for unused variables/constants/functions/types

run:
  timeout: 5m
  tests: true
  build-tags:
    - nogohook
    - notray

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: The io/ioutil package has been deprecated, see https://go.dev/doc/go1.16#ioutil
  revive:
    rules:
      - name: package-comments
        disabled: true
  goimports:
    local-prefixes: github.com/SphereStacking/silentcast
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  unparam:
    check-exported: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    
    # Exclude godot in comments with URLs
    - linters:
        - godot
      source: "https?://"
    
    # Exclude linters for generated files
    - path: "(^|/)vendor/"
      linters:
        - typecheck
    
    # Exclude specific messages
    - text: "exported .* should have comment or be unexported"
      linters:
        - revive
    
    # Exclude intentionally ignored errors in notification queue draining
    - path: internal/notify/queue\.go
      linters:
        - errcheck
      source: "q\\.manager\\.(Notify|NotifyWithOutput)"
    
    # Exclude intentionally ignored errors in Linux service manager
    - path: internal/service/manager_linux\.go
      linters:
        - errcheck
      source: "m\\.execRun"
    
    # Exclude progress reporter writes (best effort)
    - path: internal/updater/progress\.go
      linters:
        - errcheck
      source: "pw\\.reporter\\.Write"
    
    # Exclude browser detection errors (handled by nil checks)
    - path: internal/action/browser/
      linters:
        - errcheck
      source: "GetDefaultBrowser"
    
    # Exclude test cleanup errors
    - path: test/e2e/framework\.go
      linters:
        - errcheck
      source: "StopApplication"
    
    # Exclude update notifier errors (best effort notifications)
    - path: internal/notify/updater\.go
      linters:
        - errcheck
      source: "m\\.(NotifyUpdateFailed|notifier\\.NotifyUpdate)"