name: Build Development

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'app/**'
      - '.github/workflows/build-dev.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows-amd64
            goos: windows
            goarch: amd64
          
          - os: macos-latest
            name: darwin-amd64
            goos: darwin
            goarch: amd64
            
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache-dependency-path: app/go.sum
    
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew list pkg-config || brew install pkg-config
    
    - name: Build with CGO
      shell: bash
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 1
      run: |
        cd app
        go build -o silentcast-${{ matrix.name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./cmd/silentcast
    
    - name: List build output (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd app
        Get-ChildItem silentcast-*
    
    - name: List build output (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd app
        ls -lah silentcast-*
        file silentcast-*
        ldd silentcast-* || true
    
    - name: Test binary (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd app
        .\silentcast-${{ matrix.name }}.exe --version
    
    - name: Test binary (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd app
        ./silentcast-${{ matrix.name }} --version || true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: silentcast-${{ matrix.name }}
        path: app/silentcast-${{ matrix.name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        retention-days: 7